//  data type a collection of data values, usually with a set of possible values, allowed operations, and/or a representation as machine types
//  primitive
// non primitive

// primitive
// NUmebr
// bigint
// boolean
// string
// undefined
// ṇull
// symbol

// non primitive

// Object
// Array
// Function

// Number
const boy_age = 23;

// BigInt
const boy_income = 23888888299292992992992n;

// boolean

const boy_true = true;

// string
const boy_name = "mayank";

// undefined
const boy_skill = undefined;

// null
const boy_goal = null;

//  symbol

const boy_symbol = Symbol("keys");

// non primitive
 console.table([boy_age,boy_income,boy_true,boy_name,boy_skill,boy_goal,boy_symbol]);
const user = {
  name: "mukul",
  age: 23,
  tyepe: "software enginer",
  skill:
    "C/C++ or javascript ,os,networking, dsa , vs ,python , ros , arduino , maths, webdevelopment, ai ml , neural network makeing connection",
      
}

// this is object

function print(name){
    console.log(`${name}, ! :-D  hello budy`);

}

print("mukul")

// this is function

let fuction_list=["caller","wifi","bluetooth","sensor","actuator", "power manager", "camera" , "lidar" , "pump"]
console.log(fuction_list);



